[package]
name = "pktstrings"
version = "0.2.2"
edition = "2021"
rust-version = "1.60"
authors = ["Pete Wicken <petew1356@gmail.com>"]
description = "Like Unix 'strings' command but packet-aware"
repository = "https://github.com/JamoBox/pktstrings"
license = "MIT"
keywords = ["packet-analyzer", "network-monitoring", "network-analysis", "ctf-tools"]
categories = ["command-line-utilities", "network-programming"]

[dependencies]
clap = {version = "4", features = ["derive", "cargo"]}
pcap = "0"
colored = "2"
num = "0"
dns-lookup = {version = "1", optional = true}
cfg-if = "1"
libc = "0"

[features]
bland = ["colored/no-color"]
resolve = ["dns-lookup"]

[profile.release]
lto = true
